### PR TITLE
Chrome Support

### PR DESCRIPTION
**Pull request by trypsynth**
I have successfully made AxSHammer work with Chrome! There's now a Firefox folder and a Chrome folder, with Safari hopefully coming soon. All my testing seems to have worked. Some of the code for this was from Oriol's pull request, but I way improved it. Let me know if there are any issues.

### CODE REVIEW

**Comment by jcsteh** [comment]
Thanks so much for your work on this and for submitting it for inclusion. A major concern I have here is that this would mean we end up having two entirely separate code bases to maintain. This is not something I'm personally willing to do, as it means when I make changes to one, I have to make the same changes (but slightly differently) in the other.

I see two paths forward on this:

1. Try to make the extension compatible with both browsers using the same code base. The [WebExtension browser API Polyfill](https://github.com/mozilla/webextension-polyfill/) should make this possible.
2. Maintain these as two entirely separate extensions in separate repositories. I wouldn't have any involvement with the maintenance of the Chrome extension, but I'd of course be very happy for you to base it off my code and to answer any questions you might have.

I'd be keen for your thoughts on this.

**Comment by trypsynth** [comment]
Oh yeah, true. Although the codebases aren't that different, they still are, so fair enough. I'll have to do some looking into WebExtension.

**Comment by trypsynth** [comment]
Hi,
It looks like we can install this polyfill in two ways.
1. NPM
2. Downloading it and putting directly into the repo.
Which would you prefer I use? I'm not sure how NPM plays with extensions, but who knows, maybe it doesn't at all.

**Comment by trypsynth** [comment]
@jcsteh, I'm closing this. I eventually want to make an entirely cross-browser (i.e. Chrome, Firefox, and Safari) version of AxSHammer, but that's outside the scope of this PR, and its also time I don't have. Might open one in the future, though if I ever get around to it.

**Comment by jcsteh** [comment]
Sorry I didn't respond to your question in https://github.com/jcsteh/axSHammer/pull/4#issuecomment-851045758. I vaguely recall I saw it and thought about it, but didn't have time to look into the best answer and then just never got around to replying to it.

The honest truth is that I'm not super experienced with the JS ecosystem. Npm is probably the right solution, but it also seems pretty heavy for a tiny extension like this, and I'd rather not have a ridiculously complicated deployment workflow. On the other hand, bundling the polyfill also doesn't seem great. I wonder if we could include it as a git submodule or something?

Anyway, I do appreciate your interest in contributing and I totally understand you don't have the time to pursue this right now.

**Pull request closed without merging**
